# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: reports, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

reportDetail:
  url:   /reports/reportDetail/*
  param: { module: reports, action: reportDetail }

reportType:
  url:   /reports/reportType/*
  param: { module: reports, action: reportType }

exportCsv:
  url:   /reports/exportCsv/*
  param: { module: reports, action: exportCsv }
  
importCsv:
  url:   /reports/importCsv/*
  param: { module: reports, action: importCsv }

csvfile:
  url:   /reports/csvfile/*
  param: { module: reports, action: csvfile }

login:
  url:   /reports/login/*
  param: { module: login, action: login }

logout:
  url:   /reports/logout/*
  param: { module: login, action: logout }    
  
default:
  url:   /:module/:action/*
