<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/05/22 06:30:53

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=projectmanagement',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
