<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/05/22 06:30:54
$this->security = array (
  'reporttype' => 
  array (
    'is_secure' => true,
  ),
  'importcsv' => 
  array (
    'is_secure' => true,
  ),
  'exportcsv' => 
  array (
    'is_secure' => true,
  ),
  'reportdetail' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
