<?php

/**
 * AdminTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdminTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdminTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Admin');
    }
	public function getByUserName($ssUsername)
	{
		$ssQuery = '';
		$ssQuery = Doctrine_Query::create()
			    ->select('a.*')
			    ->from('Admin a')
			    ->where('BINARY a.email = ? ',$ssUsername);
			               
		return $asUserData =  $ssQuery->fetchArray();
	}
}