<?php

/**
 * ProjectDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectDetailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectDetail');
    }
	public static function getAllProjectName()
    {
	    //$asProejctNames =  array();
	    $oQuery = Doctrine_Query::create()
	    	    ->select('p.id, p.projectname') 
				->from('ProjectDetail p');
				
		return $oQuery ;
		
		/*//$asProejctNames[0] = 'All';
		if(sizeof ($saPorjects) > 0) {
    		foreach($saPorjects as $saPorject)
    			$asProejctNames[$saPorject['id']] = $saPorject['projectname'];
    	}
    	
    	return $asProejctNames;*/
    }
	public static function getAllProject()
    {
	    $asProejctNames =  array();
	    $oQuery = Doctrine_Query::create()
	    	    ->select('p.id, p.projectname') 
				->from('ProjectDetail p');
				
		$saPorjects = $oQuery->fetchArray();
		
		$asProejctNames[''] = 'Select Project';
		if(sizeof ($saPorjects) > 0) {
    		foreach($saPorjects as $saPorject)
    			$asProejctNames[$saPorject['id']] = $saPorject['projectname'];
    	}
    	
    	return $asProejctNames;
    }
}