<?php

/**
 * TABLE2Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TABLE2Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TABLE2Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TABLE2');
    }
	public static function getAllTitle()
    {
	    $asTaskTypes =  array();
	    $oQuery = Doctrine_Query::create()
	    	    ->select('t.id, t.title') 
				->from('TABLE2 t')
				->groupBy('t.title');
				
		$asTypes = $oQuery->fetchArray();
		
		if(sizeof ($asTypes) > 0) {
    		foreach($asTypes as $astype)
    			$asTaskTypes[$astype['id']] = $astype['title'];
    	}
    	
    	return $asTaskTypes;
    }
    public static function checkDuplicate($snBeginDate = '', $snEndDate = '' , $snCountryCode = '')
    {
    	
    	$asDupData = array();
    	$oQuery = Doctrine_Query::create()
	    	    ->select('*') 
				->from('TABLE2')
				->where('begin_date = ?', $snBeginDate)
				->andwhere('end_date = ?', $snEndDate)
				->andwhere('country_code = ?', $snCountryCode);

		return $asDupData = $oQuery->fetchArray();
		
    }
    public static function insertCsvDetail($asCategory = array())
    {
    	$user = new TABLE2();
    	$user->provider = $asCategory['provider'];
    	$user->provider_country = $asCategory['provider_country'];
    	$user->sku = $asCategory['sku'];
    	$user->developer = $asCategory['developer'];
    	$user->title = $asCategory['title'];
    	$user->version = $asCategory['version'];
    	$user->product_type_identifier = $asCategory['product_type_identifier'];
    	$user->units = $asCategory['units'];
    	$user->developer_proceeds = $asCategory['developer_proceeds'];
    	$user->begin_date = $asCategory['begin_date'];
    	$user->end_date = $asCategory['end_date'];
    	$user->customer_currency = $asCategory['customer_currency'];
    	$user->country_code = $asCategory['country_code'];
    	$user->currency_of_proceeds = $asCategory['currency_of_proceeds'];
    	$user->apple_identifier = $asCategory['apple_identifier'];
    	$user->customer_price = $asCategory['customer_price'];
    	$user->promo_code = $asCategory['promo_code'];
    	$user->parent_identifier = $asCategory['parent_identifier'];
    	$user->subscription = $asCategory['subscription'];
    	$user->period = $asCategory['period'];
    	$user->save();
    }
}