<?php

/**
 * TaskTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaskTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaskType');
    }
	public static function getAllTaskType()
    {
	    $oQuery = Doctrine_Query::create()
	    	    ->select('t.id, t.tasktype') 
				->from('TaskType t');
				
		return $oQuery;
    }
	public static function getAllTask()
    {
	    $ssQuery = Doctrine_Query::create()
	    	    ->select('t.id, t.tasktype') 
				->from('TaskType t');
				
		$asTaskTypes = $ssQuery->fetchArray();
		
		if(sizeof ($asTaskTypes) > 0) {
    		foreach($asTaskTypes as $asTask)
    			$asTaskType[$asTask['id']] = $asTask['tasktype'];
    	}
    	
    	return $asTaskType;
    }
}