<?php

/**
 * UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User');
    }
	
	public function getByUserName($ssUsername)
	{
		$ssQuery = '';
		$ssQuery = Doctrine_Query::create()
			    ->select('u.*')
			    ->from('User u')
			    ->where('BINARY u.email = ? ',$ssUsername);
			               
		return $asUserData =  $ssQuery->fetchArray();
	}
	public static function getAllUser()
    {
	    //$asUserNames =  array();
	    $oQuery = Doctrine_Query::create()
	    	    ->select('u.id, u.firstname, u.lastname ') 
				->from('User u');
				
		return $oQuery;
		
		/*if(sizeof ($asNames) > 0) {
    		foreach($asNames as $asName)
    			$asUserNames[$asName['id']] = $asName['firstname']." ".$asName['lastname'];
    	}
    	
    	return $asUserNames;*/
    }
    
    
    
}