<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/05/21 09:17:50
$this->security = array (
  'homepage' => 
  array (
    'is_secure' => false,
  ),
  'addreportdetail' => 
  array (
    'is_secure' => true,
  ),
  'userreportdetail' => 
  array (
    'is_secure' => true,
  ),
  'userreport' => 
  array (
    'is_secure' => true,
  ),
  'reportlist' => 
  array (
    'is_secure' => true,
  ),
  'adduserdetail' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
