<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/05/21 12:41:54
$this->security = array (
  'adduserdetail' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
