<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProjectDetail', 'doctrine');

/**
 * BaseProjectDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $projectname
 * @property Doctrine_Collection $Reports
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getProjectname() Returns the current record's "projectname" value
 * @method Doctrine_Collection getReports()     Returns the current record's "Reports" collection
 * @method ProjectDetail       setId()          Sets the current record's "id" value
 * @method ProjectDetail       setProjectname() Sets the current record's "projectname" value
 * @method ProjectDetail       setReports()     Sets the current record's "Reports" collection
 * 
 * @package    ProjectManagment
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjectDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('projectdetail');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('projectname', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Reports', array(
             'local' => 'id',
             'foreign' => 'project_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}